dev:
  adapter:
  database:
  host:
  username:
  password:
  port:

prod:
  adapter:
  database:
  host:
  username:
  password:
  port:

test:
  adapter:
  database:
  host:
  username:
  password:
  port:
